### ISSUE TITLE
Dependency `jwk-rs` is unmaintained 

### ISSUE THREAD

**Issue by howardjohn** [maxlambrecht/rust-spiffe#112]
Currently https://github.com/nhynes/jwk-rs is a dependency, pulling in some critical crypto operations (`ring`, etc), but is seemingly abandoned. This transitively pulls in things like a 3 year old version of `ring`, etc, which is not great. Maintenance PRs against the dep are going unmerged for years: https://github.com/nhynes/jwk-rs/pull/13, etc.

It would be good to plan an alternative strategy for this dependency

**Comment by bleggett** [comment]
We should maybe just use https://github.com/Keats/jsonwebtoken
