### ISSUE TITLE
failed to run custom build command for `grpcio-sys v0.9.1+1.38.0`

### ISSUE THREAD

**Issue by huguesBouvier** [maxlambrecht/rust-spiffe#18]
Hello!

I am trying to build the example, but I am getting the following error:
Caused by:
  process didn't exit successfully: `/home/azureuser/iot-k8s-identities/target/debug/build/grpcio-sys-3d0520623fd23b3a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=grpc_wrap.cc
  cargo:rerun-if-changed=grpc
  cargo:rerun-if-env-changed=UPDATE_BIND
  cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
  cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG
  cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
  cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
  cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
  cargo:rerun-if-env-changed=CXX
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rustc-link-search=native=/home/azureuser/iot-k8s-identities/target/debug/build/libz-sys-eb95c6b5de936505/out/build
  cargo:rustc-link-search=native=/home/azureuser/iot-k8s-identities/target/debug/build/libz-sys-eb95c6b5de936505/out/lib
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = Some("/home/azureuser/iot-k8s-identities/target/debug/build/libz-sys-eb95c6b5de936505/out/build")
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.9.1+1.38.0/grpc" "-DgRPC_INSTALL=false" "-DgRPC_BUILD_CSHARP_EXT=false" "-DgRPC_BUILD_CODEGEN=false" "-DgRPC_BENCHMARK_PROVIDER=none" "-DgRPC_ZLIB_PROVIDER=package" "-DCMAKE_INSTALL_PREFIX=/home/azureuser/iot-k8s-identities/target/debug/build/grpcio-sys-b62f678181885d2f/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE  
  -- Looking for res_servicename in resolv
  -- Looking for res_servicename in resolv - not found
  -- Looking for gethostbyname in nsl
  -- Looking for gethostbyname in nsl - found
  -- Looking for gethostbyname in socket
  -- Looking for gethostbyname in socket - not found
  -- Looking for socket in socket
  -- Looking for socket in socket - not found
  -- Looking for clock_gettime in rt
  -- Looking for clock_gettime in rt - found
  -- Looking for include file sys/types.h
  -- Looking for include file sys/types.h - found
  -- Looking for include file sys/socket.h
  -- Looking for include file sys/socket.h - found
  -- Looking for include file arpa/inet.h
  -- Looking for include file arpa/inet.h - found
  -- Looking for include file arpa/nameser_compat.h
  -- Looking for include file arpa/nameser_compat.h - found
  -- Looking for include file arpa/nameser.h
  -- Looking for include file arpa/nameser.h - found
  -- Looking for include file assert.h
  -- Looking for include file assert.h - found
  -- Looking for include file errno.h
  -- Looking for include file errno.h - found
  -- Looking for include file fcntl.h
  -- Looking for include file fcntl.h - found
  -- Looking for include file inttypes.h
  -- Looking for include file inttypes.h - found
  -- Looking for include file limits.h
  -- Looking for include file limits.h - found
  -- Looking for include file malloc.h
  -- Looking for include file malloc.h - found
  -- Looking for include file memory.h
  -- Looking for include file memory.h - found
  -- Looking for include file netdb.h
  -- Looking for include file netdb.h - found
  -- Looking for include file netinet/in.h
  -- Looking for include file netinet/in.h - found
  -- Looking for include file netinet/tcp.h
  -- Looking for include file netinet/tcp.h - found
  -- Looking for include file net/if.h
  -- Looking for include file net/if.h - found
  -- Looking for include file signal.h
  -- Looking for include file signal.h - found
  -- Looking for include file socket.h
  -- Looking for include file socket.h - not found
  -- Looking for include file stdbool.h
  -- Looking for include file stdbool.h - found
  -- Looking for include file stdint.h
  -- Looking for include file stdint.h - found
  -- Looking for include file stdlib.h
  -- Looking for include file stdlib.h - found
  -- Looking for include file strings.h
  -- Looking for include file strings.h - found
  -- Looking for include file string.h
  -- Looking for include file string.h - found
  -- Looking for include file stropts.h
  -- Looking for include file stropts.h - found
  -- Looking for include file sys/ioctl.h
  -- Looking for include file sys/ioctl.h - found
  -- Looking for include file sys/param.h
  -- Looking for include file sys/param.h - found
  -- Looking for include file sys/select.h
  -- Looking for include file sys/select.h - found
  -- Looking for include file sys/stat.h
  -- Looking for include file sys/stat.h - found
  -- Looking for include file sys/time.h
  -- Looking for include file sys/time.h - found
  -- Looking for include file sys/uio.h
  -- Looking for include file sys/uio.h - found
  -- Looking for include file time.h
  -- Looking for include file time.h - found
  -- Looking for include file dlfcn.h
  -- Looking for include file dlfcn.h - found
  -- Looking for include file unistd.h
  -- Looking for include file unistd.h - found
  -- Looking for include files winsock2.h, windows.h
  -- Looking for include files winsock2.h, windows.h - not found
  -- Looking for 3 include files winsock2.h, ..., windows.h
  -- Looking for 3 include files winsock2.h, ..., windows.h - not found
  -- Looking for include files winsock.h, windows.h
  -- Looking for include files winsock.h, windows.h - not found
  -- Looking for include file windows.h
  -- Looking for include file windows.h - not found
  -- Performing Test HAVE_SOCKLEN_T
  -- Performing Test HAVE_SOCKLEN_T - Success
  -- Performing Test HAVE_TYPE_SOCKET
  -- Performing Test HAVE_TYPE_SOCKET - Failed
  -- Performing Test HAVE_BOOL_T
  -- Performing Test HAVE_BOOL_T - Success
  -- Performing Test HAVE_SSIZE_T
  -- Performing Test HAVE_SSIZE_T - Success
  -- Performing Test HAVE_LONGLONG
  -- Performing Test HAVE_LONGLONG - Success
  -- Performing Test HAVE_SIG_ATOMIC_T
  -- Performing Test HAVE_SIG_ATOMIC_T - Success
  -- Performing Test HAVE_STRUCT_ADDRINFO
  -- Performing Test HAVE_STRUCT_ADDRINFO - Success
  -- Performing Test HAVE_STRUCT_IN6_ADDR
  -- Performing Test HAVE_STRUCT_IN6_ADDR - Success
  -- Performing Test HAVE_STRUCT_SOCKADDR_IN6
  -- Performing Test HAVE_STRUCT_SOCKADDR_IN6 - Success
  -- Performing Test HAVE_STRUCT_SOCKADDR_STORAGE
  -- Performing Test HAVE_STRUCT_SOCKADDR_STORAGE - Success
  -- Performing Test HAVE_STRUCT_TIMEVAL
  -- Performing Test HAVE_STRUCT_TIMEVAL - Success
  -- Looking for AF_INET6
  -- Looking for AF_INET6 - found
  -- Looking for O_NONBLOCK
  -- Looking for O_NONBLOCK - found
  -- Looking for FIONBIO
  -- Looking for FIONBIO - found
  -- Looking for SIOCGIFADDR
  -- Looking for SIOCGIFADDR - found
  -- Looking for MSG_NOSIGNAL
  -- Looking for MSG_NOSIGNAL - found
  -- Looking for PF_INET6
  -- Looking for PF_INET6 - found
  -- Looking for SO_NONBLOCK
  -- Looking for SO_NONBLOCK - not found
  -- Looking for CLOCK_MONOTONIC
  -- Looking for CLOCK_MONOTONIC - found
  -- Performing Test HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID
  -- Performing Test HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID - Success
  -- Performing Test HAVE_LL
  -- Performing Test HAVE_LL - Success
  -- Looking for bitncmp
  -- Looking for bitncmp - not found
  -- Looking for closesocket
  -- Looking for closesocket - not found
  -- Looking for CloseSocket
  -- Looking for CloseSocket - not found
  -- Looking for connect
  -- Looking for connect - found
  -- Looking for fcntl
  -- Looking for fcntl - found
  -- Looking for freeaddrinfo
  -- Looking for freeaddrinfo - found
  -- Looking for getaddrinfo
  -- Looking for getaddrinfo - found
  -- Looking for getenv
  -- Looking for getenv - found
  -- Looking for gethostbyaddr
  -- Looking for gethostbyaddr - found
  -- Looking for gethostbyname
  -- Looking for gethostbyname - found
  -- Looking for gethostname
  -- Looking for gethostname - found
  -- Looking for getnameinfo
  -- Looking for getnameinfo - found
  -- Looking for getservbyport_r
  -- Looking for getservbyport_r - found
  -- Looking for gettimeofday
  -- Looking for gettimeofday - found
  -- Looking for if_indextoname
  -- Looking for if_indextoname - found
  -- Looking for inet_net_pton
  -- Looking for inet_net_pton - not found
  -- Looking for inet_ntop
  -- Looking for inet_ntop - found
  -- Looking for inet_pton
  -- Looking for inet_pton - found
  -- Looking for ioctl
  -- Looking for ioctl - found
  -- Looking for ioctlsocket
  -- Looking for ioctlsocket - not found
  -- Looking for IoctlSocket
  -- Looking for IoctlSocket - not found
  -- Looking for recv
  -- Looking for recv - found
  -- Looking for recvfrom
  -- Looking for recvfrom - found
  -- Looking for send
  -- Looking for send - found
  -- Looking for setsockopt
  -- Looking for setsockopt - found
  -- Looking for socket
  -- Looking for socket - found
  -- Looking for strcasecmp
  -- Looking for strcasecmp - found
  -- Looking for strcmpi
  -- Looking for strcmpi - not found
  -- Looking for strdup
  -- Looking for strdup - found
  -- Looking for stricmp
  -- Looking for stricmp - not found
  -- Looking for strncasecmp
  -- Looking for strncasecmp - found
  -- Looking for strncmpi
  -- Looking for strncmpi - not found
  -- Looking for strnicmp
  -- Looking for strnicmp - not found
  -- Looking for writev
  -- Looking for writev - found
  -- Looking for __system_property_get
  -- Looking for __system_property_get - not found
  -- Found ZLIB: /home/azureuser/iot-k8s-identities/target/debug/build/libz-sys-eb95c6b5de936505/out/lib/libz.a (found version "1.2.11") 
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /home/azureuser/iot-k8s-identities/target/debug/build/grpcio-sys-b62f678181885d2f/out/build
  running: "cmake" "--build" "." "--target" "grpc_unsecure" "--config" "Debug" "--parallel" "4"

  --- stderr
  CMake Warning at cmake/protobuf.cmake:51 (message):
    gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
  Call Stack (most recent call first):
    CMakeLists.txt:255 (include)

  CMake Warning at cmake/ssl.cmake:55 (message):
    gRPC_SSL_PROVIDER is "module" but BORINGSSL_ROOT_DIR is wrong
  Call Stack (most recent call first):
    CMakeLists.txt:257 (include)

  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS

  Unknown argument --parallel
  Unknown argument 4
  Usage: cmake --build <dir> [options] [-- [native-options]]
  Options:
    <dir>          = Project binary directory to be built.
    --target <tgt> = Build <tgt> instead of default targets.
                     May only be specified once.
    --config <cfg> = For multi-configuration tools, choose <cfg>.
    --clean-first  = Build target 'clean' first, then build.
                     (To clean only, use --target 'clean'.)
    --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
    --             = Pass remaining options to the native tool.
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Do you know what this could be?

Thanks!
  
  
  PS: Aside from the example, my crate is empty:
  [dependencies]
spiffe = "0.2.0"

**Comment by maxlambrecht** [comment]
Hi Hughes! 

The dependency `grpcio` needs CMake: https://github.com/tikv/grpc-rs#prerequisites

Try installing CMake and let me know if you can build the project.

**Comment by huguesBouvier** [comment]
Thanks! I had cmake but looking at your link it requires cmake > 3.12. But default version installed by apt-get install is 3.10.
It is flagged in their git hub issue list: https://github.com/alexcrichton/cmake-rs/issues/131
 This worked for me:
[dependencies]
cmake = "=0.1.45"


Thanks a lot!
